### ISSUE TITLE
docker-compose up -d fails with....

### ISSUE THREAD

**Issue by spydmobile** [creecros/resourcespace-docker#6]
`
4e2184d41a26: Pull complete
ddb7d7fb48b7: Pull complete
Digest: sha256:b10491ddebf75a03e3831fc9947c51c496a48eba29b2a69433661401d96bb0c6
Status: Downloaded newer image for creecros/resourcespace-docker:latest
Creating resourcespace-docker_mysql-resourcespace_1 ...
Creating resourcespace-docker_resourcespace_1       ... error

ERROR: for resourcespace-docker_resourcespace_1  Cannot create container for service resourcespaCreating resourcespace-docker_mysql-resourcespace_1 ... done
'bind': no such file or directory

ERROR: for resourcespace  Cannot create container for service resourcespace: error while mounting volume with options: type='none' device='/mnt/resourcespace/include' o='bind': no such file or directory
ERROR: Encountered errors while bringing up the project.
[sparcsadmin@bp31c7 resourcespace-docker]$
`

**Comment by creecros** [comment]
Looks like your issue is with binding the volume. Does the directory exist? Do you have permissions?

**Comment by spydmobile** [comment]
I dont know, the script I ran would have had to make one for it to work. I gave up on it when it would not run out of the box and thought I would report the issue, but I did not review it exhaustively beyond noting that in my clean environment, it did not run.

**Comment by creecros** [comment]
It's ok, pretty sure that was your issue since it states it in your error log, just needed to actually create the folder before you try to bind to it. You can't bind to a folder that doesn't exist.

```error while mounting volume with options: type='none' device='/mnt/resourcespace/include' o='bind': no such file or directory```

**Comment by spydmobile** [comment]
I was under the assumption that the script needed to do that, not the user - hence the bug report. if not, well then my bad and perhaps such pre reqs need to be clearly indicated in the instructions.
Cheers

**Comment by creecros** [comment]
there's no script that can read a persons mind as to where they want to mount a volume, and no where in the dockerfile did I make that decision for you, but it would make sense that you lazily copied the composer **example** that I provided:
![image](https://user-images.githubusercontent.com/26339368/56614066-14f51400-65e6-11e9-8453-e414fd2514ff.png)

I'd be happy to change that mount path in the example to: /mnt/to/your/path instead, but would your error simply change to?
```error while mounting volume with options: type='none' device='/mnt/to/your/path include' o='bind': no such file or directory```

No idea...
